# Generated by Django 6.0.5 on 2026-05-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_ordering_verbose_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('thumbnail_image', models.ImageField(upload_to='certificates/thumbs/%Y/%m/', verbose_name='Превью')),
                ('pdf', models.FileField(upload_to='certificates/pdf/%Y/%m/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(blank=True, help_text='Например: НАДЕЖНОСТЬ — крупная подпись на фоне слайда', max_length=128, verbose_name='Тип (акцент на слайде)'),
        ),
    ]
