# Generated by Django 6.0.5 on 2026-06-17 04:47

from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(Model, instance, source: str) -> str:
    raw = slugify(str(source).strip(), allow_unicode=True)
    base = raw[:255].strip('-') or f'item-{instance.pk}'
    candidate = base
    suffix = 1
    qs = Model.objects.exclude(pk=instance.pk)
    while qs.filter(slug=candidate).exists():
        tail = f'-{suffix}'
        candidate = f'{base[: 255 - len(tail)]}{tail}'
        suffix += 1
    return candidate


def populate_news_slugs(apps, schema_editor):
    News = apps.get_model('content', 'News')
    for obj in News.objects.all():
        if not obj.slug:
            obj.slug = _unique_slug(News, obj, obj.title)
            obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_banner_type_and_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description (до 500 символов).', max_length=500, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Заголовок для <title>. Если пусто — подставляется на фронтенде.', max_length=255, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description для поисковиков (до 500 символов).', max_length=500, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Заголовок для <title> и поисковиков. Если пусто — подставляется название на сайте.', max_length=255, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, help_text='Часть адреса страницы. Если пусто — создаётся автоматически.', max_length=255, null=True, verbose_name='URL (slug)'),
        ),
        migrations.RunPython(populate_news_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Часть адреса страницы. Если пусто — создаётся автоматически.', max_length=255, unique=True, verbose_name='URL (slug)'),
        ),
    ]
