# Generated by Django 6.0.5 on 2026-06-17 12:33

import django.db.models.deletion
from django.db import migrations, models


def copy_content_seo(apps, schema_editor):
    AboutCompany = apps.get_model('content', 'AboutCompany')
    AboutCompanySeo = apps.get_model('content', 'AboutCompanySeo')
    News = apps.get_model('content', 'News')
    NewsSeo = apps.get_model('content', 'NewsSeo')

    for about in AboutCompany.objects.all():
        AboutCompanySeo.objects.create(
            about=about,
            seo_title=about.seo_title or '',
            seo_description=about.seo_description or '',
        )

    for news in News.objects.all():
        NewsSeo.objects.create(
            news=news,
            seo_title=news.seo_title or '',
            seo_description=news.seo_description or '',
            slug=news.slug or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanySeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Заголовок для <title>. Если пусто — подставляется на фронтенде.', max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, help_text='Meta description (до 500 символов).', max_length=500, verbose_name='SEO описание')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_record', to='content.aboutcompany', verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'SEO страницы',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='NewsSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Заголовок для <title> и поисковиков. Если пусто — подставляется название на сайте.', max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, help_text='Meta description для поисковиков (до 500 символов).', max_length=500, verbose_name='SEO описание')),
                ('slug', models.SlugField(blank=True, help_text='Часть адреса страницы. Если пусто — создаётся автоматически.', max_length=255, unique=True, verbose_name='URL (slug)')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_record', to='content.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'SEO новости',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.RunPython(copy_content_seo, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
