# Generated by Django 6.0.5 on 2026-05-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('email_spare_parts', models.EmailField(blank=True, max_length=254, verbose_name='Email — запчасти')),
                ('email_tires', models.EmailField(blank=True, max_length=254, verbose_name='Email — шины')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контакты сайта',
                'verbose_name_plural': 'Контакты сайта',
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Обращение (форма сайта)',
                'verbose_name_plural': 'Обращения (форма сайта)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, max_length=500, verbose_name='Telegram')),
                ('max_link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка (MAX)')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Подпись (например, запчасти / шины)')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='leads.contact', verbose_name='Контактный блок')),
            ],
            options={
                'verbose_name': 'Контактный телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ('ordering', 'id'),
            },
        ),
    ]
