# Generated by Django 6.0.5 on 2026-05-15 23:44

from django.db import migrations, models


def mark_existing_orders_as_seen_by_moderator(apps, schema_editor):
    Order = apps.get_model('commerce', 'Order')
    # Старые записи считаем уже обработанными (False = просмотрено модератором)
    Order.objects.all().update(is_seen_moderator=False)


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen_moderator',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Новая заявка для модератора'),
        ),
        migrations.RunPython(mark_existing_orders_as_seen_by_moderator, migrations.RunPython.noop),
    ]
