# Generated by Django 6.0.5 on 2026-05-18 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_ordering_verbose_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.FileField(help_text='JPG, PNG, WebP, GIF или SVG.', upload_to='manufacturers/logos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'gif', 'svg'), message='Допустимые форматы: %(allowed_extensions)s.')], verbose_name='Логотип (карточка)'),
        ),
    ]
