# Generated by Django 6.0.5 on 2026-06-17 12:33

import django.db.models.deletion
from django.db import migrations, models


def copy_commerce_seo(apps, schema_editor):
    Manufacturer = apps.get_model('commerce', 'Manufacturer')
    ManufacturerSeo = apps.get_model('commerce', 'ManufacturerSeo')
    Product = apps.get_model('commerce', 'Product')
    ProductSeo = apps.get_model('commerce', 'ProductSeo')

    for manufacturer in Manufacturer.objects.all():
        ManufacturerSeo.objects.create(
            manufacturer=manufacturer,
            seo_title=manufacturer.seo_title or '',
            seo_description=manufacturer.seo_description or '',
            slug=manufacturer.slug or '',
        )

    for product in Product.objects.all():
        ProductSeo.objects.create(
            product=product,
            seo_title=product.seo_title or '',
            seo_description=product.seo_description or '',
            slug=product.slug or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Заголовок для <title> и поисковиков. Если пусто — подставляется название на сайте.', max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, help_text='Meta description для поисковиков (до 500 символов).', max_length=500, verbose_name='SEO описание')),
                ('slug', models.SlugField(blank=True, help_text='Часть адреса страницы. Если пусто — создаётся автоматически.', max_length=255, unique=True, verbose_name='URL (slug)')),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_record', to='commerce.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'SEO производителя',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='ProductSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Заголовок для <title> и поисковиков. Если пусто — подставляется название на сайте.', max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, help_text='Meta description для поисковиков (до 500 символов).', max_length=500, verbose_name='SEO описание')),
                ('slug', models.SlugField(blank=True, help_text='Часть адреса страницы. Если пусто — создаётся автоматически.', max_length=255, unique=True, verbose_name='URL (slug)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_record', to='commerce.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'SEO товара',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.RunPython(copy_commerce_seo, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='manufacturer',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
